# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'

networks:
  backend:
    name: gallery
    driver: bridge

services:
  # Database Service (Postgres)
  db:
    # Use the Docker Image postgres. This will pull the 16.2 version.
    image: postgres:16.2
    # Give the container the name postgres-db. You can change to something else.
    container_name: gallery-db
    # Set a volume some that database is not lost after shutting down the container.
    restart: always
    # To set up the username, password, and database name. You can change these values.
    environment:
      POSTGRES_DB: gallery-db
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
    # Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    networks:
      - backend