# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)
version: '3.8'

networks:
  backend:
    name: aimaginarium
    driver: bridge

services:
  # App backend service
  app:
    image: aimaginarium-app
    # Give the container the name web-app. You can change to something else.
    container_name: aimaginarium-app
    # Build based on Dockerfile at the same directory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    # This service depends on postgres. Start that first.
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1m
      timeout: 10s
      retries: 5
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/gallery-db
    stdin_open: true
    networks:
      - backend

  # Database Service (Postgres)
  db:
    # Use the Docker Image postgres. This will pull the 16.2 version.
    image: postgres:16.2
    # Give the container the name postgres-db. You can change to something else.
    container_name: gallery-db
    # Set a volume some that database is not lost after shutting down the container.
    restart: always
    # To set up the username, password, and database name. You can change these values.
    environment:
      POSTGRES_DB: gallery-db
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
    # Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "5432:5432"
    networks:
      - backend